"""ESG Compliance PDF report."""
from __future__ import annotations
import io
from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart

router = APIRouter(prefix="/reports", tags=["reports"])

I18N = {
    "en": {"title":"SORA.Earth - Compliance Report","gen":"Generated","overview":"Project overview",
           "name":"Name","cat":"Category","reg":"Region","budget":"Budget, EUR",
           "co2":"CO2 reduction, t/y","social":"Social impact (0-10)","dur":"Duration, months",
           "overall":"Overall ESG score","pillar":"Pillar","score":"Score",
           "env":"Environmental","soc":"Social","gov":"Governance",
           "fw":"Framework alignment","fwh":"Framework","status":"Status",
           "disc":"Disclaimer","disc_t":"Generated by SORA.Earth AI Platform. Heuristic scores; not legal advice."},
    "ru": {"title":"SORA.Earth - Otchet o sootvetstvii","gen":"Sozdan","overview":"Opisanie proekta",
           "name":"Nazvanie","cat":"Kategoriya","reg":"Region","budget":"Byudzhet, EUR",
           "co2":"Snizhenie CO2, t/god","social":"Sotsialnyy effekt (0-10)","dur":"Dlitelnost, mes",
           "overall":"Itogovyy ESG ball","pillar":"Izmerenie","score":"Ball",
           "env":"Ekologicheskiy","soc":"Sotsialnyy","gov":"Upravlencheskiy",
           "fw":"Sootvetstvie freymvorkam","fwh":"Freymvork","status":"Status",
           "disc":"Disclaimer","disc_t":"Sgenerirovano SORA.Earth AI Platform."},
}

class ProjectInput(BaseModel):
    name: str
    budget: float = Field(ge=0)
    co2_reduction: float = Field(ge=0)
    social_impact: float = Field(ge=0, le=10)
    duration_months: int = Field(ge=1)
    category: str
    region: str
    description: Optional[str] = None

def _score(p):
    env = min(100.0, p.co2_reduction / 10.0 + 40.0)
    social = p.social_impact * 10.0
    governance = 70.0 + (10.0 if p.budget >= 100000 else 0.0) + (10.0 if p.duration_months >= 12 else 0.0)
    overall = round((env + social + governance) / 3.0, 1)
    es = (env + social) / 2.0
    fw = {
        "EU Taxonomy": (round(env,1), "Aligned" if env>=70 else "Partial"),
        "CSRD (ESRS E1)": (round(env,1), "Compliant" if env>=75 else "Needs work"),
        "SFDR Article 9": (round(es,1), "Eligible" if es>=70 else "Article 8"),
        "GRI Standards": (round(social,1), "Compliant" if social>=60 else "Partial"),
        "TCFD": (round(governance,1), "Compliant" if governance>=70 else "Partial"),
    }
    return {"overall":overall,"env":round(env,1),"social":round(social,1),
            "governance":round(governance,1),"frameworks":fw}

def _esg_chart(env, social, gov):
    d = Drawing(400, 180)
    bc = VerticalBarChart()
    bc.x = 50; bc.y = 30; bc.height = 130; bc.width = 320
    bc.data = [[env, social, gov]]
    bc.categoryAxis.categoryNames = ["Environmental","Social","Governance"]
    bc.bars[0].fillColor = colors.HexColor("#0B5FFF")
    bc.valueAxis.valueMin = 0; bc.valueAxis.valueMax = 100; bc.valueAxis.valueStep = 20
    d.add(bc)
    return d

@router.post("/compliance.pdf", summary="Generate ESG/CSRD compliance PDF")
def compliance_pdf(project: ProjectInput, lang: str = Query("en", pattern="^(en|ru)$")):
    t = I18N.get(lang, I18N["en"])
    res = _score(project)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm, title=t["title"])
    s = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=s["Heading1"], textColor=colors.HexColor("#0B5FFF"))
    h2 = ParagraphStyle("H2", parent=s["Heading2"])
    body = s["BodyText"]
    story = [Paragraph(t["title"], h1),
             Paragraph(t["gen"] + ": " + datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), body),
             Spacer(1, 0.5*cm), Paragraph(t["overview"], h2)]
    proj = [[t["name"], project.name],[t["cat"], project.category],[t["reg"], project.region],
            [t["budget"], "{:,.0f}".format(project.budget)],
            [t["co2"], "{:,.0f}".format(project.co2_reduction)],
            [t["social"], str(project.social_impact)],[t["dur"], str(project.duration_months)]]
    t1 = Table(proj, colWidths=[5*cm, 10*cm])
    t1.setStyle(TableStyle([("GRID",(0,0),(-1,-1),0.3,colors.grey),
                            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),
                            ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#EEF3FF"))]))
    story += [t1, Spacer(1, 0.5*cm),
              Paragraph(t["overall"] + ": <b>" + str(res["overall"]) + "/100</b>", h2),
              _esg_chart(res["env"], res["social"], res["governance"]), Spacer(1, 0.3*cm)]
    t2 = Table([[t["pillar"], t["score"]],[t["env"], res["env"]],
                [t["soc"], res["social"]],[t["gov"], res["governance"]]], colWidths=[7*cm,4*cm])
    t2.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0B5FFF")),
                            ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                            ("GRID",(0,0),(-1,-1),0.3,colors.grey),
                            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold")]))
    story += [t2, Spacer(1, 0.5*cm), Paragraph(t["fw"], h2)]
    rows = [[t["fwh"], t["score"], t["status"]]]
    for k,(sc,st) in res["frameworks"].items():
        rows.append([k, sc, st])
    t3 = Table(rows, colWidths=[7*cm,3*cm,5*cm])
    t3.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0B5FFF")),
                            ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                            ("GRID",(0,0),(-1,-1),0.3,colors.grey),
                            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
                            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#F5F8FF")])]))
    story += [t3, PageBreak(), Paragraph(t["disc"], h2), Paragraph(t["disc_t"], body)]
    doc.build(story)
    buf.seek(0)
    fname = "compliance_" + project.name.replace(" ","_") + "_" + lang + ".pdf"
    return StreamingResponse(buf, media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=" + fname})
