"""The ORM models must describe the database the migrations build.

Issue #88. Several migrations added objects that were never added to
app/database.py: eight `period_*` columns on country_indicator_history, the
whole `ingester_runs` table, three indexes on environmental_observations and
one on region_esg_scores. Autogenerate diffs metadata against the live schema
and reads anything it cannot see in the models as *removed*, so
`alembic revision --autogenerate` -- the command CLAUDE.md documents as the way
to make a migration -- generated 35 operations, among them:

    op.drop_table('ingester_runs')
    op.drop_column('country_indicator_history', 'period_status')      # x8
    op.drop_index('ix_environmental_observations_source_record_unique')

That last one is the partial unique index that prevents duplicate ingestion,
and the `period_*` columns hold provenance written across 90,461 production
rows which cannot be reconstructed. The migration would have looked like
ordinary autogenerated churn.

Comparing through `compare_metadata` runs the same comparison the command runs:
alembic/env.py configures the context with `target_metadata` and no
`include_object`, `compare_type` or `compare_server_default` overrides, so
there is nothing here for a filter to diverge from.
"""

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext

from app.database import Base
from tests.postgres_scratch import (  # noqa: F401  (scratch_db is a fixture)
    requires_postgres,
    scratch_db,
)

pytestmark = requires_postgres


def _describe(diff):
    """Render one alembic diff entry readably.

    Entries are either a tuple whose first element names the operation, or a
    list of such tuples for multi-column alterations.
    """
    if isinstance(diff, list):
        return "; ".join(_describe(d) for d in diff)
    op = diff[0]
    rest = ", ".join(
        getattr(x, "name", None) or str(x)
        for x in diff[1:]
        if x is not None
    )
    return f"{op}({rest})"


def test_models_describe_the_database(scratch_db):
    """An empty diff is the only evidence the drift is closed.

    A model that merely *has* the right columns is not enough -- types,
    identity and partial-index predicates all show up here, and each one that
    differs becomes a destructive operation in the next generated migration.
    """
    engine, _ = scratch_db

    with engine.connect() as conn:
        context = MigrationContext.configure(conn)
        diffs = compare_metadata(context, Base.metadata)

    assert diffs == [], (
        "the ORM models no longer describe the migrated schema, so the next "
        "`alembic revision --autogenerate` will emit these as changes -- "
        "anything the models omit becomes a drop:\n  "
        + "\n  ".join(_describe(d) for d in diffs)
    )
