"""A badge reports; it does not assert.

Three of the four badges at the top of the README were hand-written images:

    tests-375/384 passing   the suite had been running 2025 tests for months
    version-v0.2.1          the latest release was v0.3.0
    CI-passing-success      a static picture of the word "passing", displayed
                            whether or not CI passed

The third is the one that mattered. A badge that cannot fail is decoration
claiming to be evidence -- a reader takes it as the state of the build, and it
would have said `passing` through every red run this repository has had.

The other two are the same defect in a slower form: a number written by hand
drifts from the thing it describes, and nothing notices. This file is what
notices.
"""
import os
import re

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(REPO_ROOT, "README.md")

#: shields.io images whose text is fixed at write time. Fine for a fact that
#: changes only when someone edits the repository -- the licence -- and wrong
#: for anything observed.
_STATIC_BADGE = re.compile(r"img\.shields\.io/badge/([^)\s]+)")

#: Words that make a claim about a state nobody re-checks: build results, test
#: counts, uptime.
_CLAIMS_A_STATE = re.compile(
    r"passing|failing|success|failed|live|up|down|\d+%|\d+%2F\d+|tests?-\d",
    re.IGNORECASE,
)


@pytest.fixture(scope="module")
def readme():
    with open(README, encoding="utf-8") as fh:
        return fh.read()


def test_no_static_badge_claims_an_observed_state(readme):
    """The licence may be a static badge. A build result may not."""
    offenders = [
        text for text in _STATIC_BADGE.findall(readme)
        if _CLAIMS_A_STATE.search(text)
    ]

    assert offenders == [], (
        f"these badges are fixed images asserting something nobody re-checks: "
        f"{offenders}. Use the workflow badge for CI and a release badge for "
        f"the version; both are generated from the thing they describe."
    )


def test_the_ci_badge_comes_from_the_workflow(readme):
    """Generated by GitHub from the run, so it cannot be green while CI is
    red."""
    assert "actions/workflows/ci.yml/badge.svg" in readme


def test_there_is_exactly_one_ci_badge(readme):
    """There were two: a real one and a fixed image of the word `passing`.

    Two badges for one fact is how a reader ends up believing the wrong one.
    """
    assert readme.count("ci.yml/badge.svg") == 1


#: Every image URL in the file, badge or not.
_IMAGE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)")


def test_no_badge_carries_a_test_count(readme):
    """A count in an image is a claim with a date on it, and the date is never
    written down.

    Scoped to images rather than to the whole file: the note explaining which
    badges were removed names the old figure, and a check over the prose would
    have been tripped by the explanation of the thing it is checking for.
    """
    with_counts = [
        url for url in _IMAGE.findall(readme)
        if re.search(r"tests?[-_%]*\d+.*(%2F|/)\d+", url, re.IGNORECASE)
    ]

    assert with_counts == [], with_counts
