"""The Compliance Sentinel's verdict covers the text the answer carries.

`CopilotPage.tsx` renders `SENTINEL · PASS / FAIL` beside the Co-Pilot answer.
The verdict came from `_scan_text`, which read two fields:

    parts = [base.get("recommendation") or ""]
    parts.extend(base.get("risks") or [])

`executive_summary` -- the most prominent field on the page -- was not among
them, and neither was anything else. Measured 2026-09-25 over 64 inputs: three
distinct scanned texts, every verdict PASS, and none of the three could fail the
check. The detector itself works: on "funding approved for ivan@example.com,
100% guaranteed" it returns FAIL with one PII finding, two policy violations and
risk 1.0. It was pointed at text the platform writes itself from templates.

And `POST /copilot/qa` -- the one route that returns text generated by a model
rather than assembled from a template -- did not call the check at all.

So the guard covered the answers that cannot go wrong and not the one that can.

Two things pinned here:

- **every text field of the explain answer is scanned**, asserted by planting a
  violation in `executive_summary` -- reached by patching the builder, because
  the templates never echo caller text (checked: a project named
  "funding approved for ivan@example.com" appears in no field of the response);
- **the qa answer is scanned**, and its verdict is returned to the caller
  rather than computed and dropped.

The control matters as much as the assertions: a test that only planted a
violation could pass on a detector that fails everything, so the clean case is
asserted to pass in the same file.
"""
import pytest

POISON = "funding approved for ivan@example.com, 100% guaranteed"

BODY = {
    "probability": 0.275,
    "features": {"budget": 100000, "co2_reduction": 50,
                 "social_impact": 7, "duration_months": 24},
    "project": {"name": "p", "budget": 100000, "co2_reduction": 50,
                "social_impact": 7, "duration_months": 24, "region": "Germany"},
}


def test_a_clean_answer_still_passes(client):
    """The control. Without it every assertion below would hold on a sentinel
    that refused everything."""
    r = client.post("/api/v1/copilot/explain", json=BODY)
    assert r.status_code == 200, r.text
    compliance = r.json()["compliance"]

    assert compliance["passed"] is True, compliance
    assert compliance["risk_score"] == 0.0, compliance


def test_a_violation_in_the_executive_summary_is_caught(client, monkeypatch):
    """The field the page shows first was outside the scan.

    Patched at the builder rather than fed through the request, because the
    templates do not echo caller text -- there is no input that puts a phrase
    into this field.
    """
    import app.services.copilot as copilot

    original = copilot.explain_prediction

    def poisoned(*args, **kwargs):
        out = original(*args, **kwargs)
        if isinstance(out, dict):
            out["executive_summary"] = POISON
        return out

    monkeypatch.setattr("app.api.copilot_api.explain_prediction", poisoned)

    r = client.post("/api/v1/copilot/explain", json=BODY)
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["executive_summary"] == POISON, "the patch did not reach the response"

    compliance = body["compliance"]
    assert not compliance["passed"], (
        "the answer carries a funding-approval phrase and an email address in "
        "executive_summary, and the sentinel reported PASS -- the badge on the "
        "page is a verdict on text nobody scanned"
    )
    assert compliance["policy_violations"], compliance
    assert compliance["pii_findings"], compliance


def test_the_qa_answer_is_scanned(client, monkeypatch):
    """`/copilot/qa` returns model-generated text; it was not scanned at all."""
    monkeypatch.setattr(
        "app.api.copilot_api.answer_qa",
        lambda **_kw: {"answer": POISON, "mode": "gpt", "tokens_used": 7},
    )

    started = client.post("/api/v1/copilot/explain", json=BODY)
    assert started.status_code == 200, started.text
    session_id = started.json().get("session_id")
    assert session_id, "no session to ask a question in"

    r = client.post("/api/v1/copilot/qa",
                    json={"session_id": session_id, "question": "why?"})
    assert r.status_code == 200, r.text
    body = r.json()

    assert body["answer"] == POISON, "the patched answer did not reach the response"
    assert "compliance" in body, (
        "the qa answer carries no compliance verdict at all, so the route that "
        "returns generated text is the one route nothing guards"
    )
    assert not body["compliance"]["passed"], body["compliance"]
