"""add_country_indicator_history

Revision ID: 963bec0d1503
Revises: 94d781c78478
Create Date: 2026-04-09 18:16:35.956064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963bec0d1503'
down_revision: Union[str, Sequence[str], None] = '94d781c78478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_indicator_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_iso3', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('indicator_code', sa.String(length=100), nullable=False),
    sa.Column('indicator_name', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_job_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_indicator_history_as_of_date'), 'country_indicator_history', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_country_iso3'), 'country_indicator_history', ['country_iso3'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_country_name'), 'country_indicator_history', ['country_name'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_fetched_at'), 'country_indicator_history', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_id'), 'country_indicator_history', ['id'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_indicator_code'), 'country_indicator_history', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_country_indicator_history_source'), 'country_indicator_history', ['source'], unique=False)
    op.create_table('data_refresh_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('country_iso3', sa.String(length=10), nullable=True),
    sa.Column('indicator', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('countries_fetched', sa.Integer(), nullable=True),
    sa.Column('total_countries', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_refresh_log_id'), 'data_refresh_log', ['id'], unique=False)
    op.create_index(op.f('ix_data_refresh_log_timestamp'), 'data_refresh_log', ['timestamp'], unique=False)
    op.create_table('predictions_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('co2_reduction', sa.Float(), nullable=True),
    sa.Column('social_impact', sa.Float(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('esg_total_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_log_id'), 'predictions_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_log_id'), table_name='predictions_log')
    op.drop_table('predictions_log')
    op.drop_index(op.f('ix_data_refresh_log_timestamp'), table_name='data_refresh_log')
    op.drop_index(op.f('ix_data_refresh_log_id'), table_name='data_refresh_log')
    op.drop_table('data_refresh_log')
    op.drop_index(op.f('ix_country_indicator_history_source'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_indicator_code'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_id'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_fetched_at'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_country_name'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_country_iso3'), table_name='country_indicator_history')
    op.drop_index(op.f('ix_country_indicator_history_as_of_date'), table_name='country_indicator_history')
    op.drop_table('country_indicator_history')
    # ### end Alembic commands ###
