#!/usr/bin/env python3
"""Emit a deterministic archive. Not a real dump -- nothing here parses one."""
import os
import sys

log = os.environ.get("FAKE_PG_LOG")
if log:
    with open(log, "a") as fh:
        fh.write("pg_dump " + " ".join(sys.argv[1:]) + "\n")

body = os.environ.get("FAKE_PG_DUMP_BYTES", "PGDMP-fake-archive-v1\n" + "x" * 4096)
sys.stdout.buffer.write(body.encode())
