"""Build a throwaway database in production's *current* shape, for restore drills.

Production's region_esg_scores predates the migration chain: it was created by
an older SQLAlchemy create_all(), so region_code is the primary key, the score
columns are real, and id is a plain bigint that is not the key. The ORM has
since moved on. A restore drill is only worth anything if it exercises the
shape the data is actually in today, so this reproduces that divergence
deliberately rather than building the canonical schema.

Everything here is synthetic. This script never reads from, connects to, or
copies production.

Usage:
    DATABASE_URL=postgresql://user:pass@host:port/db python scripts/drill_seed_prod_shape.py
"""
import os
import random
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import sqlalchemy as sa

# The revision production reports; the drill asserts it survives the round trip.
PROD_ALEMBIC_REVISION = "0b0ff6d1594e"
ROW_COUNT = 85
RANDOM_SEED = 20260728  # fixed so two drills seed byte-identical data

# region_code as PK, real score columns, id as a non-key bigint identity.
LEGACY_TABLE_SQL = """
DROP VIEW IF EXISTS regional_esg_snapshot;
DROP TABLE IF EXISTS region_esg_scores CASCADE;

CREATE TABLE region_esg_scores (
    region_code   text PRIMARY KEY,
    env_score     real,
    social_score  real,
    gov_score     real,
    total_score   real,
    confidence    real,
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    sources_count integer,
    signals_used  integer,
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ix_region_esg_scores_id ON region_esg_scores (id);
"""

# Copied verbatim from alembic/versions/a1b2c3d4e5f6_regional_esg_snapshot_view.py
# so the drill restores the same view the application reads.
VIEW_SQL = """
CREATE OR REPLACE VIEW regional_esg_snapshot AS
SELECT region_code,
       env_score    AS e_score,
       social_score AS s_score,
       gov_score    AS g_score,
       total_score  AS score,
       confidence,
       ARRAY[]::text[] AS sources_used,
       updated_at   AS computed_at
FROM region_esg_scores;
"""

ALEMBIC_SQL = """
CREATE TABLE IF NOT EXISTS alembic_version (
    version_num character varying(32) NOT NULL
        CONSTRAINT alembic_version_pkc PRIMARY KEY
);
DELETE FROM alembic_version;
INSERT INTO alembic_version (version_num) VALUES (:rev);
"""


def synthetic_rows(count=ROW_COUNT, seed=RANDOM_SEED):
    """Deterministic stand-ins for the regional scores."""
    rng = random.Random(seed)
    for n in range(1, count + 1):
        env, soc, gov = (round(rng.uniform(20, 95), 2) for _ in range(3))
        yield {
            "region_code": f"RU-{n:03d}",
            "env_score": env,
            "social_score": soc,
            "gov_score": gov,
            "total_score": round((env + soc + gov) / 3, 2),
            "confidence": round(rng.uniform(0.4, 0.99), 3),
            "sources_count": rng.randint(1, 9),
            "signals_used": rng.randint(1, 40),
        }


def main():
    url = os.environ.get("DATABASE_URL")
    if not url:
        sys.exit("DATABASE_URL is required")
    if not url.startswith("postgresql"):
        sys.exit(f"refusing to seed a non-PostgreSQL target: {url}")

    from app.database import Base

    engine = sa.create_engine(url)

    # The rest of the application schema comes from the ORM; only
    # region_esg_scores is then forced back to production's older shape.
    Base.metadata.create_all(engine)

    with engine.begin() as conn:
        conn.execute(sa.text("SET client_min_messages TO WARNING"))
        for statement in filter(None, (s.strip() for s in LEGACY_TABLE_SQL.split(";"))):
            conn.execute(sa.text(statement))
        conn.execute(sa.text(VIEW_SQL))
        for statement in filter(None, (s.strip() for s in ALEMBIC_SQL.split(";"))):
            conn.execute(sa.text(statement), {"rev": PROD_ALEMBIC_REVISION})

        rows = list(synthetic_rows())
        conn.execute(
            sa.text(
                "INSERT INTO region_esg_scores "
                "(region_code, env_score, social_score, gov_score, total_score,"
                " confidence, sources_count, signals_used, updated_at) VALUES "
                "(:region_code, :env_score, :social_score, :gov_score, :total_score,"
                " :confidence, :sources_count, :signals_used,"
                " TIMESTAMPTZ '2026-07-01 00:00:00+00')"
            ),
            rows,
        )

    with engine.connect() as conn:
        seeded = conn.execute(sa.text("SELECT count(*) FROM region_esg_scores")).scalar()
        revision = conn.execute(sa.text("SELECT version_num FROM alembic_version")).scalar()
        via_view = conn.execute(sa.text("SELECT count(*) FROM regional_esg_snapshot")).scalar()

    print(f"seeded rows           : {seeded}")
    print(f"alembic_version       : {revision}")
    print(f"rows through the view : {via_view}")
    if seeded != ROW_COUNT or via_view != ROW_COUNT:
        sys.exit(f"expected {ROW_COUNT} rows both directly and through the view")


if __name__ == "__main__":
    main()
